# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
name:             "bdehoyos.me"
title:            "Bruno De Hoyos"
tagline:          "Computer Science | Mechanical Engineering"
description:      'Welcome to my website! I am currently a student at <a href="http://www.utexas.edu" target="_blank">The University of Texas at Austin</a> and you can find my most recent projects here. Feel free to follow me on <a href="https://www.linkedin.com/" target="_blank">LinkedIn</a>! :]'
url:              http://localhost:4000/
paginate:         5

author:
  name:           "An author name goes here"
  url:            http://bru.uno

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bdehoyos
