# Dependencies
markdown:         kramdown
highlighter:      pygments

gems:
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Bruno De Hoyos
tagline:          '| bdehoyos.me'
description:      'Welcome to my website! This is a collection of some of my favorite personal projects. Please leave me a comment if you find anything interesting!<br>-Bruno'
url:              http://bdehoyos.me

paginate:         5

excerpt_separator: <!--more-->

author:
  name:           'Bruno De Hoyos'
  url:            http://bdehoyos.me

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/bdehoyos