# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
name:             "bdehoyos.me"
title:            "Bruno De Hoyos"
tagline:          "Computer Science | Mechanical Engineering"
description:      "A description goes here"
url:              http://localhost:4000/
paginate:         5

author:
  name:           "An author name goes here"
  url:            http://bru.uno

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bdehoyos
