# Dependencies
markdown:         kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Bruno De Hoyos
tagline:          '| bdehoyos.me'
description:      'bdehoyos.me<br>A collection of personal projects.<br><br>'
url:              http://bdehoyos.me

paginate:         7

excerpt_separator: <!--more-->

author:
  name:           'Bruno De Hoyos'
  url:            http://bdehoyos.me

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/bdehoyos