# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems:
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Bruno De Hoyos
tagline:          'Computer Science | Mechanical Engineering'
description:      'Welcome to my website! I am currently a student at <a href="http://www.utexas.edu" target="_blank">The University of Texas at Austin</a> and you can find my most recent projects here. Feel free to follow me on <a href="https://www.linkedin.com/" target="_blank">LinkedIn</a>! :]'
url:              http://bdehoyos.me
baseurl:          '/'
paginate:         10

excerpt_separator: <!--more-->

author:
  name:           'Bruno De Hoyos'
  url:            http://bdehoyos.me

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bdehoyos